# Form implementation generated from reading ui file 'snake_game.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(870, 650)
        MainWindow.setStyleSheet("background-color: white;\n"
"border: 1px solid black;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.game_table = QtWidgets.QTableWidget(self.centralwidget)
        self.game_table.setEnabled(False)
        self.game_table.setGeometry(QtCore.QRect(20, 60, 464, 464))
        self.game_table.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.CrossCursor))
        self.game_table.setMouseTracking(True)
        self.game_table.setTabletTracking(True)
        self.game_table.setAutoFillBackground(False)
        self.game_table.setStyleSheet("border: 2px solid black;")
        self.game_table.setObjectName("game_table")
        self.game_table.setColumnCount(10)
        self.game_table.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.game_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.game_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.game_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.game_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.game_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.game_table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.game_table.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.game_table.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.game_table.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.game_table.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.game_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.game_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.game_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.game_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.game_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.game_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.game_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.game_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.game_table.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.game_table.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemFlag.ItemIsSelectable|QtCore.Qt.ItemFlag.ItemIsEditable|QtCore.Qt.ItemFlag.ItemIsDragEnabled|QtCore.Qt.ItemFlag.ItemIsUserCheckable|QtCore.Qt.ItemFlag.ItemIsEnabled)
        self.game_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.game_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.game_table.setItem(1, 0, item)
        self.game_table.horizontalHeader().setVisible(False)
        self.game_table.horizontalHeader().setCascadingSectionResizes(False)
        self.game_table.horizontalHeader().setDefaultSectionSize(46)
        self.game_table.verticalHeader().setVisible(False)
        self.game_table.verticalHeader().setDefaultSectionSize(46)
        self.game_table.verticalHeader().setHighlightSections(True)
        self.name_line = QtWidgets.QLineEdit(self.centralwidget)
        self.name_line.setGeometry(QtCore.QRect(210, 10, 211, 31))
        self.name_line.setStyleSheet("background-color: rgb(255, 206, 141);\n"
"font: 13pt \"JetBrains Mono\";\n"
"padding-left: 10px;\n"
"border: 2px solid black;\n"
"border-radius: 16px;")
        self.name_line.setText("")
        self.name_line.setObjectName("name_line")
        self.name_label = QtWidgets.QLabel(self.centralwidget)
        self.name_label.setGeometry(QtCore.QRect(20, 10, 181, 31))
        self.name_label.setStyleSheet("background-color: rgb(255, 206, 141);\n"
"font: 13pt \"JetBrains Mono\";\n"
"border-radius: 16px;\n"
"padding: 5px;\n"
"border: 2px solid black;")
        self.name_label.setObjectName("name_label")
        self.player1_name_label = QtWidgets.QLabel(self.centralwidget)
        self.player1_name_label.setGeometry(QtCore.QRect(20, 540, 464, 31))
        self.player1_name_label.setStyleSheet("background-color: #b6d7a8;\n"
"font: 13pt \"JetBrains Mono\";\n"
"border-radius: 16px;\n"
"padding: 5px;\n"
"border: 2px solid black;")
        self.player1_name_label.setObjectName("player1_name_label")
        self.player2_name_label = QtWidgets.QLabel(self.centralwidget)
        self.player2_name_label.setGeometry(QtCore.QRect(20, 580, 464, 31))
        self.player2_name_label.setStyleSheet("background-color: #ea9999;\n"
"font: 13pt \"JetBrains Mono\";\n"
"border-radius: 16px;\n"
"padding: 5px;\n"
"border: 2px solid black;")
        self.player2_name_label.setObjectName("player2_name_label")
        self.logger = QtWidgets.QTextBrowser(self.centralwidget)
        self.logger.setGeometry(QtCore.QRect(500, 10, 361, 601))
        self.logger.setStyleSheet("font: 13pt \"JetBrains Mono\";\n"
"border: 2px solid black;\n"
"padding: 6px;\n"
"background-color: white;")
        self.logger.setObjectName("logger")
        self.access_name_button = QtWidgets.QPushButton(self.centralwidget)
        self.access_name_button.setGeometry(QtCore.QRect(430, 10, 54, 31))
        self.access_name_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.access_name_button.setStyleSheet("background-color: rgb(255, 206, 141);\n"
"font: 14pt \"JetBrains Mono\";\n"
"border-radius: 16px;\n"
"padding: 5px;\n"
"border: 2px solid black;")
        self.access_name_button.setObjectName("access_name_button")
        self.game_over_banner = QtWidgets.QLabel(self.centralwidget)
        self.game_over_banner.setGeometry(QtCore.QRect(32, 197, 440, 190))
        self.game_over_banner.setStyleSheet("background-color: rgb(255, 206, 141);\n"
"font: 13pt \"JetBrains Mono\";\n"
"padding: 5px;\n"
"border: 2px solid black;\n"
"font-size: 30px;\n"
"\n"
"")
        self.game_over_banner.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.game_over_banner.setObjectName("game_over_banner")
        self.name_line.raise_()
        self.name_label.raise_()
        self.game_table.raise_()
        self.player1_name_label.raise_()
        self.player2_name_label.raise_()
        self.logger.raise_()
        self.access_name_button.raise_()
        self.game_over_banner.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 870, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.game_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "A"))
        item = self.game_table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "B"))
        item = self.game_table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "C"))
        item = self.game_table.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "D"))
        item = self.game_table.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "E"))
        item = self.game_table.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "F"))
        item = self.game_table.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "G"))
        item = self.game_table.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "H"))
        item = self.game_table.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "I"))
        item = self.game_table.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "J"))
        item = self.game_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.game_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.game_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.game_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.game_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.game_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.game_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.game_table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.game_table.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.game_table.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        __sortingEnabled = self.game_table.isSortingEnabled()
        self.game_table.setSortingEnabled(False)
        self.game_table.setSortingEnabled(__sortingEnabled)
        self.name_label.setText(_translate("MainWindow", "Choose your nickname:"))
        self.player1_name_label.setText(_translate("MainWindow", "Player 1: connecting and choosing nickname..."))
        self.player2_name_label.setText(_translate("MainWindow", "Player 2: connecting and choosing nickname..."))
        self.logger.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'JetBrains Mono\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.access_name_button.setText(_translate("MainWindow", "OK"))
        self.game_over_banner.setText(_translate("MainWindow", "TextLabel"))
